[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.1.7"
djangorestframework = "3.15.2"
environs = "14.1.1"
pytest = "8.3.5"
pytest-django = "4.10.0"
flake8 = "^7.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
