[project]
name = "demo_tests"
version = "0.1.0"
requires-python = ">=3.10"

[tool.poetry.dependencies]
django = "5.1.7"
djangorestframework = "3.15.2"
environs = "14.1.1"
pytest = "8.3.5"
pytest-django = "4.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
